//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunst.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CursusInschrijving
    {
        public int CursusInschrijvingId { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "VoorNaam", ResourceType = typeof(Resources.Resources))]     
        public string VoorNaam { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "LastName", ResourceType = typeof(Resources.Resources) )]
        public string AchterNaam { get; set; }

        [Display(Name = "E-mail" )]
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [Display(Name = "PhoneNumber", ResourceType = typeof(Resources.Resources) )]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
        public string TelefoonGsm { get; set; }

        public int CursusId { get; set; }

        [Required]
        [Display(Name = "AvailableTime", ResourceType = typeof(Resources.Resources) )]
        public string datum { get; set; }
    
        public virtual Cursus Cursus2 { get; set; }
    }
}
