//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunst.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Cursus
    {
        public Cursus()
        {
            this.CursusInschrijving1 = new HashSet<CursusInschrijving>();
        }
    
        public int CursusId { get; set; }

        [Display(Name = "CursusNaam", ResourceType = typeof(Resources.Resources))]  
        public string CursusNaam { get; set; }

        [Display(Name = "CursusInfo", ResourceType = typeof(Resources.Resources))]  
        public string CursusInfo { get; set; }
    
        public virtual ICollection<CursusInschrijving> CursusInschrijving1 { get; set; }
    }
}
