//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunstwerk.
        /// </summary>
        public static string Artefact {
            get {
                return ResourceManager.GetString("Artefact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschikbaar tijd.
        /// </summary>
        public static string AvailableTime {
            get {
                return ResourceManager.GetString("AvailableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        public static string Beschrijving {
            get {
                return ResourceManager.GetString("Beschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boek.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breedte.
        /// </summary>
        public static string Breedte {
            get {
                return ResourceManager.GetString("Breedte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klik hier om de kalender te openen.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleischetsen.
        /// </summary>
        public static string ClayDrawing {
            get {
                return ResourceManager.GetString("ClayDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collage.
        /// </summary>
        public static string Collage {
            get {
                return ResourceManager.GetString("Collage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURSUS.
        /// </summary>
        public static string COURSE {
            get {
                return ResourceManager.GetString("COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creëren.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatie materiaal.
        /// </summary>
        public static string Creatiemateriaal {
            get {
                return ResourceManager.GetString("Creatiemateriaal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string CursusInfo {
            get {
                return ResourceManager.GetString("CursusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursusinschrijving.
        /// </summary>
        public static string CursusInschrijving {
            get {
                return ResourceManager.GetString("CursusInschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string CursusNaam {
            get {
                return ResourceManager.GetString("CursusNaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodenmasker.
        /// </summary>
        public static string DeathMask {
            get {
                return ResourceManager.GetString("DeathMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omschrijving Beeld.
        /// </summary>
        public static string DescriptionSculpture {
            get {
                return ResourceManager.GetString("DescriptionSculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diepte.
        /// </summary>
        public static string Diepte {
            get {
                return ResourceManager.GetString("Diepte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekening.
        /// </summary>
        public static string Drawing {
            get {
                return ResourceManager.GetString("Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijheid.
        /// </summary>
        public static string Freedom {
            get {
                return ResourceManager.GetString("Freedom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoogte.
        /// </summary>
        public static string Hoogte {
            get {
                return ResourceManager.GetString("Hoogte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de Heerbeelding.
        /// </summary>
        public static string Imagery {
            get {
                return ResourceManager.GetString("Imagery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijven.
        /// </summary>
        public static string Inschrijven {
            get {
                return ResourceManager.GetString("Inschrijven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaar.
        /// </summary>
        public static string Jaar {
            get {
                return ResourceManager.GetString("Jaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log uit.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medaille.
        /// </summary>
        public static string Medal {
            get {
                return ResourceManager.GetString("Medal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schilderij.
        /// </summary>
        public static string Painting {
            get {
                return ResourceManager.GetString("Painting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poëzie.
        /// </summary>
        public static string Poetry {
            get {
                return ResourceManager.GetString("Poetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portret.
        /// </summary>
        public static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projecten.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreren.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliëf.
        /// </summary>
        public static string Relief {
            get {
                return ResourceManager.GetString("Relief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beeld.
        /// </summary>
        public static string Sculpture {
            get {
                return ResourceManager.GetString("Sculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEELDEN.
        /// </summary>
        public static string Sculptures {
            get {
                return ResourceManager.GetString("Sculptures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech.
        /// </summary>
        public static string Speech {
            get {
                return ResourceManager.GetString("Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoon.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D WERKEN.
        /// </summary>
        public static string ThreeDWorks {
            get {
                return ResourceManager.GetString("ThreeDWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan wanneer u tijd hebt.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafmonument.
        /// </summary>
        public static string Tomb {
            get {
                return ResourceManager.GetString("Tomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-D WERKEN.
        /// </summary>
        public static string TwoDWorks {
            get {
                return ResourceManager.GetString("TwoDWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitvoeringsmateriaal.
        /// </summary>
        public static string Uitvoeringsmateriaal {
            get {
                return ResourceManager.GetString("Uitvoeringsmateriaal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw inschrijving.
        /// </summary>
        public static string UwInschrijving {
            get {
                return ResourceManager.GetString("UwInschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vipa.
        /// </summary>
        public static string Vipa {
            get {
                return ResourceManager.GetString("Vipa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        public static string VoorNaam {
            get {
                return ResourceManager.GetString("VoorNaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GESCHREVEN WERKEN.
        /// </summary>
        public static string WRITTENWORKS {
            get {
                return ResourceManager.GetString("WRITTENWORKS", resourceCulture);
            }
        }
    }
}
